### ISSUE TITLE
error if .pre-commit-config.yaml exists in git repo but file was deleted

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/precommend#8]
```
Traceback (most recent call last):
  File "/home/lkeegan/.pyenv/versions/3.9.15/lib/python3.9/site-packages/identify/identify.py", line 42, in tags_from_path
    sr = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '.pre-commit-config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkeegan/.pyenv/versions/3.9.15/bin/precommend", line 8, in <module>
    sys.exit(main())
  File "/home/lkeegan/.pyenv/versions/3.9.15/lib/python3.9/site-packages/precommend/__main__.py", line 11, in main
    ctx = GenerationContext()
  File "/home/lkeegan/.pyenv/versions/3.9.15/lib/python3.9/site-packages/precommend/core.py", line 14, in __init__
    self._tags = functools.reduce(
  File "/home/lkeegan/.pyenv/versions/3.9.15/lib/python3.9/site-packages/identify/identify.py", line 44, in tags_from_path
    raise ValueError(f'{path} does not exist.')
ValueError: .pre-commit-config.yaml does not exist.

```

**Comment by dokempf** [comment]
Could also filter the files found in Git again for their existence in the working copy.
